import type { Shot } from "../types";
import { applyPoseControlOverride, buildPoseControlFromPlan, derivePoseScenePlanV2, type PoseControlOverrideV1, type PoseControlV2, type PoseInteractionInput, type PoseScenePlanV2 } from "../pose-v2";
import { chooseProjectionV3, projectionHashV3, transformPeopleV3 } from "./projection";
import { renderControlOpenPoseV3, renderPreviewV3 } from "./render";
import type { ActionEvidenceV3, CompositionKindV3, CompositionPolicyV3, PoseControlV3, PoseRelationPlanV3, PoseScenePlanV3 } from "./schema";
import { templateForV3 } from "./templates";
import { assertProjectionConsistencyV3, validatePoseSceneV3 } from "./validation";
const stableHash=(value:unknown)=>{const s=JSON.stringify(value);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,"0")};
export type BuildPoseV3Options={compositionPolicy?:CompositionPolicyV3;preferredComposition?:CompositionKindV3;width?:number;height?:number};
function buildWalkGeometryV3(people:PoseControlV2["people"],plans:Array<{primaryAction:string;locomotion:PoseScenePlanV2["people"][number]["locomotion"];relationTargets:PoseScenePlanV2["people"][number]["relationTargets"];mirror?:boolean}>){const result=JSON.parse(JSON.stringify(people)) as PoseControlV2["people"];result.forEach((p,index)=>{const plan=plans[index],gait=plan?.locomotion;if(!p||plan.primaryAction!=="locomotion"||!gait||gait.mode!=="walk")return;const cx=(p[8].x+p[11].x)/2;const supportRight=gait.supportSide==="right";const support={hip:supportRight?8:11,knee:supportRight?9:12,ankle:supportRight?10:13,side:supportRight?-1:1};const swing={hip:supportRight?11:8,knee:supportRight?12:9,ankle:supportRight?13:10,side:supportRight?1:-1};const stride=Math.max(.16,gait.stride);const lift=gait.gaitPhase==="toe_off"?.1:gait.gaitPhase==="mid_stance"?.065:.025;p[support.hip]={x:cx+support.side*.045,y:.52};p[support.knee]={x:cx+support.side*.025,y:.71};p[support.ankle]={x:cx+support.side*.04,y:.91};p[swing.hip]={x:cx+swing.side*.05,y:.515};p[swing.knee]={x:cx+swing.side*stride*.85,y:gait.gaitPhase==="heel_strike"?.7:.65};p[swing.ankle]={x:cx+swing.side*stride,y:.91-lift};const forwardArm=supportRight?{shoulder:2,elbow:3,wrist:4,side:-1}:{shoulder:5,elbow:6,wrist:7,side:1};const rearArm=supportRight?{shoulder:5,elbow:6,wrist:7,side:1}:{shoulder:2,elbow:3,wrist:4,side:-1};p[forwardArm.elbow]={x:cx+forwardArm.side*.105,y:.39};p[forwardArm.wrist]={x:cx+forwardArm.side*.055,y:.48};p[rearArm.elbow]={x:cx+rearArm.side*.13,y:.43};p[rearArm.wrist]={x:cx+rearArm.side*.17,y:.55};const occupied=new Set(plan.relationTargets.flatMap(r=>r.activeHand==="both"?["left","right"]:[r.activeHand]));if(occupied.has("right")){p[3]=people[index][3];p[4]=people[index][4]}if(occupied.has("left")){p[6]=people[index][6];p[7]=people[index][7]}p[1]={x:cx+support.side*.018,y:.27};p[0]={x:cx+support.side*.012,y:.16};if(plan.mirror)for(const point of p)point.x=cx-(point.x-cx)});return result}
export function derivePoseScenePlanV3(shot:Shot,interactions:PoseInteractionInput[]=[],options:BuildPoseV3Options={}):PoseScenePlanV3|null{
 const legacy=derivePoseScenePlanV2(shot,interactions);if(!legacy)return null;const policy=options.compositionPolicy||"auto_story";const fullLegacy:PoseScenePlanV2=JSON.parse(JSON.stringify(legacy));fullLegacy.framingMode="full_body";fullLegacy.framingGeometry={mode:"full_body",scale:1,visibleBoundsTarget:{x:.04,y:.04,width:.92,height:.92},source:"default"};fullLegacy.people.forEach(p=>{if(p.locomotion)p.locomotion.lowerBodyControl="full"});
 const fullControl=buildPoseControlFromPlan(fullLegacy,options.width||512,options.height||512);const people=fullLegacy.people.map(p=>{const template=templateForV3(p.primaryAction,p.sourceText);const actionEvidence:ActionEvidenceV3[]=template?.evidence||[{id:`${p.characterId}-pose`,kind:"joint",required:true,jointIndices:[0,1,2,5],description:"人物动作上身证据"}];return{...p,templateId:template?.id||p.templateId,secondaryActions:p.actions.filter(x=>x!==p.primaryAction),supportHand:p.activeHand==="both"?"left" as const:null,supportLeg:p.locomotion?.supportSide||null,targetId:p.gazeTarget.targetId,emotionIntent:shot.visualSpec?.characters.find(x=>x.characterId===p.characterId)?.expression||"",actionEvidence,source:shot.visualSpecConfirmed?{kind:"confirmed_visual_spec" as const,detail:"shot.visualSpec"}:{kind:"legacy_text" as const,detail:"shot action/camera text"},confidenceScore:p.sourceText?.trim()?.length?.82:.45}});
 const fullPeople=buildWalkGeometryV3(fullControl.people,fullLegacy.people);const relations:PoseRelationPlanV3[]=interactions.map((x,i)=>({...x,relationId:x.relationId||`relation-${shot.id}-${i+1}`,objectInstanceId:x.objectInstanceId||`object-${shot.id}-${i+1}`,stateBefore:null,stateAfter:null,occlusionOrder:[x.characterId,x.objectInstanceId||x.object]}));const relationEvidence:ActionEvidenceV3[]=relations.filter(x=>x.required).map(x=>({id:`relation:${x.relationId}`,kind:"relation",required:true,relationId:x.relationId,description:`${x.characterId} ${x.purpose} ${x.object}`}));const evidence=[...people.flatMap(p=>p.actionEvidence.map(x=>({...x,id:`${p.characterId}:${x.id}`}))),...relationEvidence];const projection=chooseProjectionV3(fullPeople,evidence,policy,options.preferredComposition);const inputHash=stableHash({shotId:shot.id,visualSpec:shot.visualSpecConfirmed?shot.visualSpec:null,interactions,policy,preferred:options.preferredComposition,seed:legacy.variantSeed});const templateHash=stableHash(people.map(p=>({id:p.templateId,phase:p.phase,intensity:p.intensity,mirror:p.mirror})));
 return{...fullLegacy,schemaVersion:"3.0",plannerVersion:"pose-v3.0.0",compositionPolicy:policy,people,relations,evidence,fullPeople,projection,decisionReasons:[legacy.selectorReason,"walk geometry uses explicit support/swing legs, lifted foot, pelvis weight shift and contralateral arm swing",projection?`${projection.composition} selected with score ${projection.score.toFixed(2)}`:"no valid composition"],status:projection?"planned":interactions.some(x=>x.required)?"needs_pose_edit":"needs_story_clarification",inputHash,templateHash,projectionHash:projectionHashV3(projection)};
}
export function buildPoseControlV3(shot:Shot,interactions:PoseInteractionInput[]=[],options:BuildPoseV3Options={}):PoseControlV3|null{const width=options.width||512,height=options.height||512;const plan=derivePoseScenePlanV3(shot,interactions,{...options,width,height});if(!plan||!plan.projection)return null;const projected=transformPeopleV3(plan.fullPeople,plan.projection.scale,plan.projection.translate);const safety=validatePoseSceneV3(plan);safety.errors.push(...assertProjectionConsistencyV3(plan,projected));safety.valid=safety.errors.length===0;const controlPeople=projected.map((p,pi)=>p.map((q,ji)=>plan.projection!.visibility[pi]?.[ji]==="visible"?q:{x:-1,y:-1}));const svg=renderControlOpenPoseV3(projected,plan.projection.visibility,width,height);const allLower=plan.projection.visibility.every(v=>[8,9,10,11,12,13].every(j=>v[j]==="visible"));return{kind:`pose_v3_${plan.projection.composition}`,posePlanVersion:"3.0",framingMode:"auto_story",hiddenJointIndices:allLower?[]:[8,9,10,11,12,13].filter(j=>plan.projection!.visibility.some(v=>v[j]!=="visible")),source:"automatic_story_plan",selectorReason:plan.decisionReasons.join("; "),actionFamily:plan.people.map(p=>p.primaryAction).join("+"),presetId:plan.people.map(p=>p.templateId).join("+"),variantId:plan.variantSeed,scenePlan:plan,controlProfile:plan.controlProfile,override:null,safety,lowerBodyControl:allLower?"full":"projected_out_of_frame",framingWarnings:plan.projection.hardFailures,width,height,people:controlPeople,fullPeople:plan.fullPeople,visibility:plan.projection.visibility,svg,previews:{fullPoseSvg:renderPreviewV3(plan.fullPeople,plan.fullPeople.map(p=>p.map(()=>"visible")),width,height,"V3 full pose preview"),compositionSvg:renderPreviewV3(projected,plan.projection.visibility,width,height,`V3 ${plan.projection.composition}`)},artifacts:{controlOpenpose:{mimeType:"image/svg+xml",width,height,annotated:false},controlProp:{required:plan.relations.some(x=>x.required),relationIds:plan.relations.filter(x=>x.required).map(x=>x.relationId)},controlSupport:{required:plan.supportRelations.some(x=>x.supportKind!=="unknown"),supportSurfaceIds:plan.supportRelations.filter(x=>x.supportKind!=="unknown").map(x=>x.supportSurfaceId)}},audit:{inputHash:plan.inputHash,templateHash:plan.templateHash,projectionHash:plan.projectionHash,deterministic:true}}}

const v2TemplateForV3:Record<string,string>={stand:"single_stand_v2",sit:"single_sit_rise_v2",crouch:"single_crouch_kneel_v2",kneel_single:"single_crouch_kneel_v2",kneel_double:"single_crouch_kneel_v2",recline:"single_recline_v2",lie_supine:"single_lie_v2",lie_side:"single_lie_v2",walk:"single_walk_v2",run:"single_run_v2",hold_one:"single_hold_carry_v2",hold_two:"single_hold_carry_v2",phone_one:"single_read_phone_v2",phone_two:"single_read_phone_v2",pick:"single_pick_place_v2",place:"single_pick_place_v2",push:"single_push_pull_v2",pull:"single_push_pull_v2",handover:"double_handover_v2",handshake:"double_handshake_highfive_v2",highfive:"double_handshake_highfive_v2",embrace:"double_embrace_support_v2",support_walk:"double_embrace_support_v2"};
function specializeV3Geometry(people:PoseControlV2["people"],templateId:string|undefined){const result=JSON.parse(JSON.stringify(people)) as PoseControlV2["people"];const p=result[0];if(!p)return result;if(templateId==="kneel_single"){p[9].y=.72;p[10].y=.9;p[12].y=.82;p[13].y=.9}else if(templateId==="kneel_double"){p[9].y=.78;p[10].y=.9;p[12].y=.78;p[13].y=.9}else if(templateId==="crouch"){p[9].x-=.08;p[12].x+=.08;p[9].y=p[12].y=.72}else if(templateId==="push"){p[4].x+=.16;p[7].x+=.16;p[1].x+=.05}else if(templateId==="pull"){p[4].x-=.08;p[7].x-=.08;p[1].x-=.04}else if(templateId==="phone_one"){const cx=p[1].x+(p[2].x>=p[5].x?.12:-.12),cy=p[1].y+.18;p[4]={x:cx,y:cy};p[3]={x:(p[2].x+cx)/2,y:cy+.06};p[0]={x:p[0].x+(cx-p[0].x)*.12,y:p[0].y+.025}}else if(templateId==="phone_two"){const cx=p[1].x,cy=p[1].y+.2;p[4]={x:cx+.035,y:cy};p[7]={x:cx-.035,y:cy};p[3]={x:(p[2].x+cx)/2,y:cy+.06};p[6]={x:(p[5].x+cx)/2,y:cy+.06};p[0]={x:p[0].x,y:p[0].y+.035}}if(result.length===2){const a=result[0],b=result[1],mid=(a[1].x+b[1].x)/2;if(templateId==="highfive"){a[4]={x:mid-.015,y:.27};b[7]={x:mid+.015,y:.27};a[3]={x:(a[2].x+mid)/2,y:.36};b[6]={x:(b[5].x+mid)/2,y:.36}}else if(templateId==="handshake"){a[4]={x:mid-.01,y:.53};b[7]={x:mid+.01,y:.53}}else if(templateId==="embrace"){a[4]={x:b[1].x-.03,y:b[1].y+.1};b[7]={x:a[1].x+.03,y:a[1].y+.1}}else if(templateId==="support_walk"){a[4]={x:b[2].x,y:b[2].y+.04};b[7]={x:a[5].x,y:a[5].y+.05};b[1].y+=.06}}return result}

export function applyPoseControlOverrideV3(base:PoseControlV3,value:unknown):PoseControlV3{
 const raw=value&&typeof value==="object"?value as PoseControlOverrideV1:null;if(!raw)return base;const requestedV3=raw.templateId||base.scenePlan.people[0]?.templateId;const projection=base.scenePlan.projection;
 if(raw.editMode==="joint_edit"&&raw.people&&projection){
  const canvasPeople=raw.people.map((person,pi)=>person.map((point,ji)=>point.x<0||point.y<0?base.people[pi]?.[ji]||point:{x:point.x,y:point.y}));
  const fullPeople=canvasPeople.map((person,pi)=>person.map((point,ji)=>point.x<0||point.y<0?base.fullPeople[pi]?.[ji]||point:{x:(point.x-.5-projection.translate.x)/projection.scale+.5,y:(point.y-.5-projection.translate.y)/projection.scale+.5}));
  const visibility=canvasPeople.map((person,pi)=>person.map((point,ji)=>point.x<0||point.y<0?(base.visibility[pi]?.[ji]||"out_of_frame"):"visible" as const));
  const lockedProjection={...projection,id:`projection-user-locked-${stableHash({scale:projection.scale,translate:projection.translate,canvasPeople})}`,visibility,source:"user_locked" as const};
  const plan:PoseScenePlanV3=JSON.parse(JSON.stringify(base.scenePlan));plan.fullPeople=fullPeople;plan.projection=lockedProjection;plan.compositionPolicy="locked";plan.projectionHash=projectionHashV3(lockedProjection);plan.decisionReasons=[...plan.decisionReasons.filter(x=>!x.startsWith("user joint edit")),"user joint edit applied in projected_canvas coordinates with current projection locked"];
  const projected=transformPeopleV3(fullPeople,lockedProjection.scale,lockedProjection.translate);const safety=validatePoseSceneV3(plan);safety.errors.push(...assertProjectionConsistencyV3(plan,projected));safety.valid=safety.errors.length===0;const allLower=visibility.every(v=>[8,9,10,11,12,13].every(j=>v[j]==="visible"));const override={...raw,people:canvasPeople,editMode:"joint_edit" as const,coordinateSpace:"projected_canvas" as const,projectionIntent:"lock_current" as const};
  return{...base,selectorReason:plan.decisionReasons.join("; "),scenePlan:plan,override,safety,lowerBodyControl:allLower?"full":"projected_out_of_frame",hiddenJointIndices:allLower?[]:[8,9,10,11,12,13].filter(j=>visibility.some(v=>v[j]!=="visible")),people:canvasPeople,fullPeople,visibility,svg:renderControlOpenPoseV3(projected,visibility,base.width,base.height),previews:{fullPoseSvg:renderPreviewV3(fullPeople,fullPeople.map(p=>p.map(()=>"visible")),base.width,base.height,"V3 full pose preview"),compositionSvg:renderPreviewV3(projected,visibility,base.width,base.height,`V3 ${lockedProjection.composition} user locked`)},audit:{...base.audit,projectionHash:plan.projectionHash}};
 }
 const editedFull=raw.people&&projection?raw.people.map(person=>person.map(point=>point.x<0||point.y<0?point:{x:(point.x-.5-projection.translate.x)/projection.scale+.5,y:(point.y-.5-projection.translate.y)/projection.scale+.5})):raw.people;const mapped={...raw,people:editedFull,templateId:raw.templateId?v2TemplateForV3[raw.templateId]||raw.templateId:undefined};
 const legacyScene={...base.scenePlan,schemaVersion:"2.0",people:base.scenePlan.people.map(p=>({...p,templateId:v2TemplateForV3[p.templateId]||p.templateId}))} as unknown as PoseScenePlanV2;
 const legacy:PoseControlV2={kind:base.kind,posePlanVersion:"2.0",framingMode:"full_body",hiddenJointIndices:[],source:"automatic_action_plan",selectorReason:base.selectorReason,actionFamily:base.actionFamily,presetId:v2TemplateForV3[base.presetId]||base.presetId,variantId:base.variantId,scenePlan:legacyScene,controlProfile:base.controlProfile,override:null,safety:base.safety,lowerBodyControl:"full",framingWarnings:[],width:base.width,height:base.height,people:base.fullPeople,svg:base.previews.fullPoseSvg};
 const rebuilt=applyPoseControlOverride(legacy,mapped) as PoseControlV2;const plan:PoseScenePlanV3=JSON.parse(JSON.stringify(base.scenePlan));plan.people=rebuilt.scenePlan.people.map((p,i)=>({...plan.people[i],...p,templateId:i===0&&requestedV3?requestedV3:(templateForV3(p.primaryAction,p.sourceText)?.id||p.templateId)}));plan.fullPeople=buildWalkGeometryV3(specializeV3Geometry(rebuilt.people,requestedV3),plan.people);
 const preferred=raw.targetDirection?base.scenePlan.projection?.composition:undefined;plan.projection=chooseProjectionV3(plan.fullPeople,plan.evidence,plan.compositionPolicy,preferred);plan.projectionHash=projectionHashV3(plan.projection);plan.templateHash=stableHash(plan.people.map(p=>({id:p.templateId,phase:p.phase,intensity:p.intensity,mirror:p.mirror})));plan.decisionReasons=[...plan.decisionReasons.filter(x=>!x.startsWith("user override")),`user override applied: ${requestedV3||"parameters"}`];if(!plan.projection)return base;
 const projected=transformPeopleV3(plan.fullPeople,plan.projection.scale,plan.projection.translate);const visibility=plan.projection.visibility;const safety=validatePoseSceneV3(plan);safety.errors.push(...assertProjectionConsistencyV3(plan,projected));safety.valid=safety.errors.length===0;const people=projected.map((p,pi)=>p.map((q,ji)=>visibility[pi]?.[ji]==="visible"?q:{x:-1,y:-1}));const allLower=visibility.every(v=>[8,9,10,11,12,13].every(j=>v[j]==="visible"));return{...base,presetId:plan.people.map(p=>p.templateId).join("+"),selectorReason:plan.decisionReasons.join("; "),scenePlan:plan,override:null,safety,lowerBodyControl:allLower?"full":"projected_out_of_frame",hiddenJointIndices:allLower?[]:[8,9,10,11,12,13].filter(j=>visibility.some(v=>v[j]!=="visible")),people,fullPeople:plan.fullPeople,visibility,svg:renderControlOpenPoseV3(projected,visibility,base.width,base.height),previews:{fullPoseSvg:renderPreviewV3(plan.fullPeople,plan.fullPeople.map(p=>p.map(()=>"visible")),base.width,base.height,"V3 full pose preview"),compositionSvg:renderPreviewV3(projected,visibility,base.width,base.height,`V3 ${plan.projection.composition}`)},audit:{...base.audit,templateHash:plan.templateHash,projectionHash:plan.projectionHash}};
}
