import {resolveActionMechanism,relocateActionGeometry} from "../../scripts/action-mechanism.mjs";
import {inferStoryActionContract} from "../story-action-contract";
import {prepareActionRelationsV3} from "./action-relations";
import {poseConditioningPolicy} from "../../scripts/pose-conditioning-policy.mjs";
import {actionGeometryV3} from "./action-geometry";
import {extraActionsV3,pairTemplateV3,pairTemplateIdsV3} from "./action-catalog";
import {configurePoseLayers,solvePoseOverlaysV3,restoreExplicitContactsV3} from "./overlays";
import { rebuildBasicPeople, BASIC_GEOMETRY_VERSION } from "./basic-geometry";
import type { Shot } from "../types";
import { applyPoseControlOverride, parsePoseControlOverride, profileForPlan, buildPoseControlFromPlan, derivePoseScenePlanV2, type PoseControlOverrideV1, type PoseControlV2, type PoseInteractionInput, type PoseScenePlanV2 } from "../pose-v2";
import { projectionFramingFailuresV3, isUpperCompositionV3, compositionForCameraV3, frameActionEvidenceV3, evaluateJointEvidenceV3, chooseProjectionV3, projectionHashV3, transformPeopleV3 } from "./projection";
import { renderControlOpenPoseV3, renderPreviewV3 } from "./render";
import type { ActionEvidenceV3, CompositionKindV3, CompositionPolicyV3, PoseControlV3, PoseRelationPlanV3, PoseScenePlanV3 } from "./schema";
import { poseTemplateRegistryV3, templateForV3 } from "./templates";
import { assertProjectionConsistencyV3, validatePoseSceneV3 } from "./validation";
const stableHash=(value:unknown)=>{const s=JSON.stringify(value);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,"0")};
export type BuildPoseV3Options={compositionPolicy?:CompositionPolicyV3;preferredComposition?:CompositionKindV3;width?:number;height?:number};
function solveActionPeople(people:PoseControlV2["people"],plans:PoseScenePlanV3["people"],relations:PoseRelationPlanV3[]=[]){const posed=actionGeometryV3(rebuildBasicPeople(people,plans),plans);prepareActionRelationsV3(posed,plans,relations);return solvePoseOverlaysV3(posed,plans);}
function buildWalkGeometryV3(people:PoseControlV2["people"],_plans:unknown){return people.map(p=>p.map(q=>({...q})));}

export function derivePoseScenePlanV3(shot:Shot,interactions:PoseInteractionInput[]=[],options:BuildPoseV3Options={}):PoseScenePlanV3|null{
 interactions=interactions.map((r,i)=>({...r,relationId:r.relationId||`relation-${shot.id}-${i+1}`})); const legacy=derivePoseScenePlanV2(shot,interactions);if(!legacy)return null;const policy=options.compositionPolicy||"auto_story";const preferred=options.preferredComposition||compositionForCameraV3(String((shot.visualSpecConfirmed?shot.visualSpec?.camera?.shotSize:null)||shot.cameraEn||shot.camera||""));const fullLegacy:PoseScenePlanV2=JSON.parse(JSON.stringify(legacy));fullLegacy.framingMode="full_body";fullLegacy.framingGeometry={mode:"full_body",scale:1,visibleBoundsTarget:{x:.04,y:.04,width:.92,height:.92},source:"default"};fullLegacy.people.forEach(p=>{if(p.locomotion)p.locomotion.lowerBodyControl="full"});
 restoreExplicitContactsV3(fullLegacy.people,interactions);const fullControl=buildPoseControlFromPlan(fullLegacy,options.width||512,options.height||512,true);const people:PoseScenePlanV3["people"]=fullLegacy.people.map(p=>{const template=templateForV3(p.primaryAction,p.sourceText);const actionEvidence:ActionEvidenceV3[]=template?.evidence||[{id:`${p.characterId}-pose`,kind:"joint",required:true,jointIndices:[0,1,2,5],description:"人物动作上身证据"}];return{...p,templateId:template?.id||p.templateId,secondaryActions:p.actions.filter(x=>x!==p.primaryAction),supportHand:p.activeHand==="both"?"left" as const:null,supportLeg:p.locomotion?.supportSide||null,targetId:p.gazeTarget.targetId,emotionIntent:shot.visualSpec?.characters.find(x=>x.characterId===p.characterId)?.expression||"",actionEvidence:frameActionEvidenceV3(actionEvidence,preferred),source:shot.visualSpecConfirmed?{kind:"confirmed_visual_spec" as const,detail:"shot.visualSpec"}:{kind:"legacy_text" as const,detail:"shot action/camera text"},confidenceScore:p.sourceText?.trim()?.length?.82:.45}});
 people.forEach(p=>{const canonical=p.relationTargets.find(r=>r.actionPlan)?.actionPlan;if(canonical){p.templateId=canonical.actionId;p.phase=canonical.phase;p.actionGeometryInput=canonical.geometry;}const pair=people.length===2?pairTemplateV3(fullLegacy.interactionKind,people.map(q=>q.sourceText).join(" ")):null;if(pair){p.templateId=pair;p.actionEvidence=frameActionEvidenceV3(poseTemplateRegistryV3.find(t=>t.id===pair)?.evidence||p.actionEvidence,preferred);}configurePoseLayers(p);if(/^(phone|hold)_/.test(p.templateId)&&p.layers?.armTemplateId)p.templateId=p.layers.armTemplateId;p.actionEvidence=frameActionEvidenceV3([...p.actionEvidence,...(poseTemplateRegistryV3.find(t=>t.id===p.layers?.armTemplateId)?.evidence||[])].filter((e,i,all)=>all.findIndex(q=>q.id===e.id)===i),preferred)}); if(people.length===2&&people[0].templateId==='support_walk'){
 const active=people.findIndex(p=>/\bsupporting\b|helping .*walk|搀扶|扶住|扶着/.test(p.sourceText)&&!/being supported|supported by|被.*扶/.test(p.sourceText));
 const passive=people.findIndex(p=>/being supported|supported by|被.*扶|由.*扶/.test(p.sourceText));
 const activeCount=people.filter(p=>/\bsupporting\b|helping .*walk|搀扶|扶住|扶着/.test(p.sourceText)&&!/being supported|supported by|被.*扶/.test(p.sourceText)).length;const index=activeCount===1?active:passive>=0?1-passive:-1;if(index>=0){people[index].pairRole='active';people[1-index].pairRole='supported';}
} const fullPeople=solveActionPeople(buildWalkGeometryV3(fullControl.people,fullLegacy.people),people); fullLegacy.supportRelations=people.map(p=>p.supportRelation);const relations:PoseRelationPlanV3[]=interactions.map((x,i)=>{const r=people.find(p=>p.characterId===x.characterId)?.relationTargets.find(r=>r.relationId===x.relationId);const a=r?.actionRelationAudit;return {...x,objectCenter:r?.target||x.objectCenter,contactAnchors:r?.contactAnchors||x.contactAnchors,relationId:x.relationId||`relation-${shot.id}-${i+1}`,objectInstanceId:x.objectInstanceId||`object-${shot.id}-${i+1}`,actionRelationAudit:a,stateBefore:a?.stateBefore||null,stateAfter:a?.stateAfter||null,occlusionOrder:[x.characterId,x.objectInstanceId||x.object]};});const relationEvidence:ActionEvidenceV3[]=relations.filter(x=>x.required).map(x=>({id:`relation:${x.relationId}`,kind:"relation",required:true,personIndex:people.findIndex(p=>p.characterId===x.characterId),jointIndices:x.handMode==="two"?[4,7]:[x.activeHand==="left"?7:4],points:[x.objectCenter,...(x.actionRelationAudit?.geometry?.outline||[]).flatMap(p=>p.points)],propFootprint:x.shape==="umbrella"||x.actionRelationAudit?.geometry?.outline?.length?undefined:{shape:x.shape||"",orientation:x.orientation||"",contactSpan:x.contactAnchors?.length?Math.max(...x.contactAnchors.map(a=>a.x))-Math.min(...x.contactAnchors.map(a=>a.x)):0,hasPoseContact:Boolean(x.contactAnchors?.length),regionWidth:x.region.xEnd-x.region.xStart},relationId:x.relationId,description:`${x.characterId} ${x.purpose} ${x.object}`}));const evidence=[...people.flatMap((p,personIndex)=>p.actionEvidence.map(x=>({...x,personIndex,id:`${p.characterId}:${x.id}`}))),...relationEvidence];const projection=chooseProjectionV3(fullPeople,evidence,policy,preferred);fullLegacy.controlProfile=poseConditioningPolicy(profileForPlan(fullLegacy.peopleCount,projection&&isUpperCompositionV3(projection.composition)?"upper_body":"full_body",people),people);const inputHash=stableHash({shotId:shot.id,visualSpec:shot.visualSpecConfirmed?shot.visualSpec:null,interactions,policy,preferred,seed:legacy.variantSeed});const templateHash=stableHash({geometryVersion:BASIC_GEOMETRY_VERSION,people:people.map(p=>({id:p.templateId,phase:p.phase,intensity:p.intensity,mirror:p.mirror,basic:p.basicGeometry})),fullPeople});
 return{...fullLegacy,schemaVersion:"3.0",plannerVersion:"pose-v3.3.0",compositionPolicy:policy,preferredComposition:preferred,people,relations,evidence,fullPeople,projection,decisionReasons:[legacy.selectorReason,"walk geometry uses explicit support/swing legs, lifted foot, pelvis weight shift and contralateral arm swing",projection?`${projection.composition} selected with score ${projection.score.toFixed(2)}`:"no valid composition"],status:projection?"planned":interactions.some(x=>x.required)?"needs_pose_edit":"needs_story_clarification",inputHash,templateHash,projectionHash:projectionHashV3(projection)};
}
export function buildPoseControlV3(shot:Shot,interactions:PoseInteractionInput[]=[],options:BuildPoseV3Options={}):PoseControlV3|null{const width=options.width||512,height=options.height||512;const plan=derivePoseScenePlanV3(shot,interactions,{...options,width,height});if(!plan||!plan.projection)return null;const projected=transformPeopleV3(plan.fullPeople,plan.projection.scale,plan.projection.translate);const safety=validatePoseSceneV3(plan);safety.errors.push(...assertProjectionConsistencyV3(plan,projected));safety.valid=safety.errors.length===0;plan.status=safety.valid?"planned":"needs_pose_edit";const controlPeople=projected.map((p,pi)=>p.map((q,ji)=>plan.projection!.visibility[pi]?.[ji]==="visible"?q:{x:-1,y:-1}));const svg=renderControlOpenPoseV3(projected,plan.projection.visibility,width,height);const allLower=plan.projection.visibility.every(v=>[8,9,10,11,12,13].every(j=>v[j]==="visible"));return{kind:`pose_v3_${plan.projection.composition}`,posePlanVersion:"3.0",framingMode:"auto_story",hiddenJointIndices:allLower?[]:[8,9,10,11,12,13].filter(j=>plan.projection!.visibility.some(v=>v[j]!=="visible")),source:"automatic_story_plan",selectorReason:plan.decisionReasons.join("; "),actionFamily:plan.people.map(p=>p.primaryAction).join("+"),presetId:plan.people.map(p=>p.templateId).join("+"),variantId:plan.variantSeed,scenePlan:plan,controlProfile:plan.controlProfile,override:null,safety,lowerBodyControl:allLower?"full":"projected_out_of_frame",framingWarnings:plan.projection.hardFailures,width,height,people:controlPeople,fullPeople:plan.fullPeople,visibility:plan.projection.visibility,svg,previews:{fullPoseSvg:renderPreviewV3(plan.fullPeople,plan.fullPeople.map(p=>p.map(()=>"visible")),width,height,"V3 full pose preview"),compositionSvg:renderPreviewV3(projected,plan.projection.visibility,width,height,`V3 ${plan.projection.composition}`)},artifacts:{controlOpenpose:{mimeType:"image/svg+xml",width,height,annotated:false},controlProp:{required:plan.relations.some(x=>x.required),relationIds:plan.relations.filter(x=>x.required).map(x=>x.relationId)},controlSupport:{required:plan.supportRelations.some(x=>x.supportKind!=="unknown"),supportSurfaceIds:plan.supportRelations.filter(x=>x.supportKind!=="unknown").map(x=>x.supportSurfaceId)}},audit:{inputHash:plan.inputHash,templateHash:plan.templateHash,projectionHash:plan.projectionHash,deterministic:true}}}

const v2TemplateForV3:Record<string,string>={...Object.fromEntries(pairTemplateIdsV3.map(id=>[id,`double_${id}_v2`])),...Object.fromEntries(Object.entries(extraActionsV3).map(([id,a])=>[id,`single_${a.family}_v2`])),lie_prone:"single_lie_v2",stand:"single_stand_v2",sit:"single_sit_rise_v2",crouch:"single_crouch_kneel_v2",kneel_single:"single_crouch_kneel_v2",kneel_double:"single_crouch_kneel_v2",recline:"single_recline_v2",lie_supine:"single_lie_v2",lie_side:"single_lie_v2",walk:"single_walk_v2",run:"single_run_v2",hold_one:"single_hold_carry_v2",hold_two:"single_hold_carry_v2",phone_one:"single_read_phone_v2",phone_two:"single_read_phone_v2",pick:"single_pick_place_v2",place:"single_pick_place_v2",push:"single_push_pull_v2",pull:"single_push_pull_v2",handover:"double_handover_v2",handshake:"double_handshake_highfive_v2",highfive:"double_handshake_highfive_v2",embrace:"double_embrace_support_v2",support_walk:"double_embrace_support_v2"};

export function applyPoseControlOverrideV3(base:PoseControlV3,value:unknown):PoseControlV3{
 const input=value&&typeof value==="object"?value as PoseControlOverrideV1:null;const raw=input?{...parsePoseControlOverride({...input,people:undefined})!,...(Array.isArray(input.people)?{people:input.people}:{})}:null;if(!raw)return base;if(raw.conditioning && Object.keys(raw).every(k=>["schemaVersion","conditioning"].includes(k))){const profile=poseConditioningPolicy(base.controlProfile,base.scenePlan.people,raw.conditioning);return {...base,controlProfile:profile,scenePlan:{...base.scenePlan,controlProfile:profile},override:{...base.override,...raw,coordinateSpace:base.override?.coordinateSpace||"full_pose",projectionIntent:base.override?.projectionIntent||"recompute"}};}if(raw.editMode==="joint_edit"&&raw.coordinateSpace==="full_pose"&&["templateId","bodyTemplateId","armTemplateId","mirror","bodyView","kneeSpacing","phase","intensity","handedness","targetDirection","spacing","swapRoles"].some(k=>(raw as any)[k]!==undefined)){base=applyPoseControlOverrideV3(base,{...raw,people:undefined,editMode:"parameter_edit",projectionIntent:"recompute"});}const requestedV3=raw.templateId||base.scenePlan.people[0]?.templateId;const projection=base.scenePlan.projection;
 if(raw.editMode==="joint_edit"&&raw.people&&projection){
  const canvasPeople=raw.coordinateSpace==="full_pose"?transformPeopleV3(raw.people,projection.scale,projection.translate):raw.people.map((person,pi)=>person.map((point,ji)=>point.x<0||point.y<0?base.people[pi]?.[ji]||point:{x:point.x,y:point.y}));
  const fullPeople=raw.coordinateSpace==="full_pose"?raw.people.map(p=>p.map(q=>({...q}))):canvasPeople.map((person,pi)=>person.map((point,ji)=>point.x<0||point.y<0?base.fullPeople[pi]?.[ji]||point:{x:(point.x-.5-projection.translate.x)/projection.scale+.5,y:(point.y-.5-projection.translate.y)/projection.scale+.5}));
  const visibility=transformPeopleV3(fullPeople,projection.scale,projection.translate).map(person=>person.map(point=>point.x>=.02&&point.x<=.98&&point.y>=.02&&point.y<=.98?"visible" as const:"out_of_frame" as const));
  const evidenceVisible=evaluateJointEvidenceV3(fullPeople.length?transformPeopleV3(fullPeople,projection.scale,projection.translate):[],base.scenePlan.evidence,projection);
  const hardFailures=base.scenePlan.evidence.filter(e=>e.required&&!evidenceVisible[e.id]).map(e=>`required evidence out of frame: ${e.id}`);hardFailures.push(...projectionFramingFailuresV3(transformPeopleV3(fullPeople,projection.scale,projection.translate),projection.composition));
  const lockedProjection={...projection,evidenceVisible,hardFailures,id:`projection-user-locked-${stableHash({scale:projection.scale,translate:projection.translate,canvasPeople})}`,visibility,source:"user_locked" as const};
  const plan:PoseScenePlanV3=JSON.parse(JSON.stringify(base.scenePlan));plan.controlProfile=poseConditioningPolicy(base.controlProfile,plan.people,raw.conditioning);plan.fullPeople=fullPeople;plan.templateHash=stableHash({geometryVersion:plan.plannerVersion,layers:plan.people.map(p=>p.layers),fullPeople});plan.people.forEach((person,i)=>{if(person.overlayAudit){person.overlayAudit.arms.forEach(a=>{const s=a.hand==="left"?5:2;const distance=Math.hypot(fullPeople[i][s].x-a.target.x,fullPeople[i][s].y-a.target.y);a.reachable=distance<=a.upperLength+a.foreLength+1e-8&&distance>=Math.abs(a.upperLength-a.foreLength)-1e-8;a.error=a.reachable?null:a.error;});person.overlayAudit.errors=person.overlayAudit.errors.filter(e=>!e.includes("contact target is beyond arm reach"));}});plan.projection=lockedProjection;plan.compositionPolicy="locked";plan.projectionHash=projectionHashV3(lockedProjection);plan.decisionReasons=[...plan.decisionReasons.filter(x=>!x.startsWith("user joint edit")),"user joint edit applied with current projection locked"];
  const projected=transformPeopleV3(fullPeople,lockedProjection.scale,lockedProjection.translate);const safety=validatePoseSceneV3(plan);safety.errors.push(...assertProjectionConsistencyV3(plan,projected));safety.valid=safety.errors.length===0;plan.status=safety.valid?"planned":"needs_pose_edit";const allLower=visibility.every(v=>[8,9,10,11,12,13].every(j=>v[j]==="visible"));const override={...raw,people:raw.coordinateSpace==="full_pose"?fullPeople:canvasPeople,editMode:"joint_edit" as const,coordinateSpace:raw.coordinateSpace==="full_pose"?"full_pose" as const:"projected_canvas" as const,projectionIntent:"lock_current" as const};
  return{...base,selectorReason:plan.decisionReasons.join("; "),scenePlan:plan,controlProfile:plan.controlProfile,override,safety,framingWarnings:lockedProjection.hardFailures,lowerBodyControl:allLower?"full":"projected_out_of_frame",hiddenJointIndices:allLower?[]:[8,9,10,11,12,13].filter(j=>visibility.some(v=>v[j]!=="visible")),people:canvasPeople,fullPeople,visibility,svg:renderControlOpenPoseV3(projected,visibility,base.width,base.height),previews:{fullPoseSvg:renderPreviewV3(fullPeople,fullPeople.map(p=>p.map(()=>"visible")),base.width,base.height,"V3 full pose preview"),compositionSvg:renderPreviewV3(projected,visibility,base.width,base.height,`V3 ${lockedProjection.composition} user locked`)},audit:{...base.audit,templateHash:plan.templateHash,projectionHash:plan.projectionHash}};
 }
 const editedFull=raw.people&&projection?raw.people.map(person=>person.map(point=>point.x<0||point.y<0?point:{x:(point.x-.5-projection.translate.x)/projection.scale+.5,y:(point.y-.5-projection.translate.y)/projection.scale+.5})):raw.people;const mapped={...raw,people:editedFull,templateId:raw.templateId&&!/^(hold|phone)_(one|two)$/.test(raw.templateId)?v2TemplateForV3[raw.templateId]||raw.templateId:raw.bodyTemplateId?v2TemplateForV3[raw.bodyTemplateId]:undefined};
 const legacyScene={...base.scenePlan,schemaVersion:"2.0",people:base.scenePlan.people.map(p=>({...p,templateId:v2TemplateForV3[p.templateId]||p.templateId}))} as unknown as PoseScenePlanV2;
 const legacy:PoseControlV2={kind:base.kind,posePlanVersion:"2.0",framingMode:"full_body",hiddenJointIndices:[],source:"automatic_action_plan",selectorReason:base.selectorReason,actionFamily:base.actionFamily,presetId:v2TemplateForV3[base.presetId]||base.presetId,variantId:base.variantId,scenePlan:legacyScene,controlProfile:base.controlProfile,override:null,safety:base.safety,lowerBodyControl:"full",framingWarnings:[],width:base.width,height:base.height,people:base.fullPeople,svg:base.previews.fullPoseSvg};
 const rebuilt=applyPoseControlOverride(legacy,mapped,true) as PoseControlV2;const plan:PoseScenePlanV3=JSON.parse(JSON.stringify(base.scenePlan));plan.people=rebuilt.scenePlan.people.map((p,i)=>({...plan.people[i],...p,templateId:(i===0||plan.peopleCount===2)&&requestedV3?requestedV3:(templateForV3(p.primaryAction,p.sourceText)?.id||p.templateId)}));if(raw.swapRoles&&plan.people.length===2){plan.people.forEach((p,i)=>{p.pairRole=(base.scenePlan.people[i].pairRole||(i===0?"active":"supported"))==="active"?"supported":"active";p.source={kind:"manual",detail:"explicit swapped interaction roles"};});}restoreExplicitContactsV3(plan.people,plan.relations);plan.people.forEach((p,i)=>configurePoseLayers(p,base.scenePlan.people[i],i===0||pairTemplateIdsV3.includes(raw.templateId||"")?raw:{...raw,templateId:undefined,bodyTemplateId:undefined,armTemplateId:undefined}));plan.plannerVersion="pose-v3.3.0";if(raw.templateId&&plan.people[0]){const person=plan.people[0];const r=person.relationTargets.find(r=>r.actionPlan||r.purpose==='operate'||['pick','place'].includes(raw.templateId||''));if(r){const inferred=inferStoryActionContract({object:r.object,expectedCount:r.actionPlan?.geometry.objectCount,purpose:r.purpose,objectCenter:r.actionPlan?.geometry.baseCenter||r.target,region:{xStart:0,xEnd:1}},person.sourceText,raw.phase||person.phase,false,raw.templateId);if(inferred){person.actionGeometryInput=inferred.geometry;person.phase=raw.phase||inferred.phase;r.actionPlan=inferred;}}}if(raw.actionGeometry&&plan.people[0]){const person=plan.people[0],own=person.relationTargets[0];let geometry=person.actionGeometryInput||{};
 if(raw.actionGeometry.mechanism&&!geometry.modelVersion&&['hinge','slide','press','rotate','force'].includes(raw.actionGeometry.mechanism)){const mechanism=raw.actionGeometry.mechanism;geometry={...geometry,modelVersion:'action-mechanism-1',mechanism,actionId:person.templateId,baseCenter:own?.target||person.anchor,controlShape:mechanism==='press'?'button':mechanism==='rotate'?'knob':mechanism==='force'?'box':'panel',axis:{x:1,y:0},extent:{width:.12,height:.12},angle:1,travel:.04,source:'manual',assumptions:['explicit manual mechanism; representative dimensions and travel']};}
 geometry=resolveActionMechanism(geometry,raw.phase||person.phase);if(raw.actionGeometry.objectCenter)geometry=relocateActionGeometry(geometry,raw.actionGeometry.objectCenter);
 person.actionGeometryInput={...geometry,...raw.actionGeometry,...(raw.actionGeometry.toolEnd?{toolEndLocked:true}:{})};}plan.people.forEach(p=>{p.basicPoseOverride={...p.basicPoseOverride,...(raw.bodyTemplateId?{templateId:raw.bodyTemplateId}:raw.templateId?{templateId:raw.templateId}:{}),...(["front","three_quarter","left_profile","right_profile"].includes(String(raw.bodyView))?{bodyView:raw.bodyView}:{}),...(["natural","together","apart"].includes(String(raw.kneeSpacing))?{kneeSpacing:raw.kneeSpacing}:{})}});const legacyGeometry=buildWalkGeometryV3(/^(hold|phone)_(one|two)$/.test(requestedV3||"")?rebuilt.people:rebuilt.people,plan.people); plan.fullPeople=solveActionPeople(legacyGeometry,plan.people,plan.relations);
 plan.supportRelations=plan.people.map(p=>p.supportRelation);plan.overrideConflicts=rebuilt.scenePlan.overrideConflicts;plan.warnings=rebuilt.scenePlan.warnings;plan.controlProfile=rebuilt.controlProfile;
 plan.people.forEach(p=>{const template=poseTemplateRegistryV3.find(t=>t.id===p.templateId);if(template)p.actionEvidence=frameActionEvidenceV3([...template.evidence,...(poseTemplateRegistryV3.find(t=>t.id===p.layers?.armTemplateId)?.evidence||[])].filter((e,i,all)=>all.findIndex(q=>q.id===e.id)===i),plan.preferredComposition)});
 plan.evidence=[...plan.people.flatMap((p,personIndex)=>p.actionEvidence.map(e=>({...e,personIndex,id:`${p.characterId}:${e.id}`}))),...plan.evidence.filter(e=>e.relationId).map(e=>({...e,points:[plan.relations.find(r=>r.relationId===e.relationId)?.objectCenter||e.points![0],...(plan.relations.find(r=>r.relationId===e.relationId)?.actionRelationAudit?.geometry?.outline||[]).flatMap(p=>p.points)]}))];
 const preferred=base.scenePlan.preferredComposition||(raw.targetDirection?base.scenePlan.projection?.composition:undefined);plan.projection=chooseProjectionV3(plan.fullPeople,plan.evidence,plan.compositionPolicy,preferred);plan.controlProfile=poseConditioningPolicy(profileForPlan(plan.peopleCount,plan.projection&&isUpperCompositionV3(plan.projection.composition)?"upper_body":"full_body",plan.people),plan.people,raw.conditioning);plan.projectionHash=projectionHashV3(plan.projection);plan.templateHash=stableHash({geometryVersion:plan.plannerVersion,people:plan.people.map(p=>({id:p.templateId,phase:p.phase,intensity:p.intensity,mirror:p.mirror,basic:p.basicGeometry})),fullPeople:plan.fullPeople});plan.decisionReasons=[...plan.decisionReasons.filter(x=>!x.startsWith("user override")),`user override applied: ${requestedV3||"parameters"}`];if(!plan.projection)return base;
 const projected=transformPeopleV3(plan.fullPeople,plan.projection.scale,plan.projection.translate);const visibility=plan.projection.visibility;const safety=validatePoseSceneV3(plan);safety.errors.push(...assertProjectionConsistencyV3(plan,projected));safety.valid=safety.errors.length===0;plan.status=safety.valid?"planned":"needs_pose_edit";const people=projected.map((p,pi)=>p.map((q,ji)=>visibility[pi]?.[ji]==="visible"?q:{x:-1,y:-1}));const allLower=visibility.every(v=>[8,9,10,11,12,13].every(j=>v[j]==="visible"));return{...base,actionFamily:plan.people.map(p=>p.actions.join("+")).join("/"),presetId:plan.people.map(p=>p.templateId).join("+"),selectorReason:plan.decisionReasons.join("; "),scenePlan:plan,controlProfile:plan.controlProfile,override:{...raw,coordinateSpace:"full_pose",projectionIntent:"recompute"},safety,framingWarnings:plan.projection.hardFailures,lowerBodyControl:allLower?"full":"projected_out_of_frame",hiddenJointIndices:allLower?[]:[8,9,10,11,12,13].filter(j=>visibility.some(v=>v[j]!=="visible")),people,fullPeople:plan.fullPeople,visibility,svg:renderControlOpenPoseV3(projected,visibility,base.width,base.height),previews:{fullPoseSvg:renderPreviewV3(plan.fullPeople,plan.fullPeople.map(p=>p.map(()=>"visible")),base.width,base.height,"V3 full pose preview"),compositionSvg:renderPreviewV3(projected,visibility,base.width,base.height,`V3 ${plan.projection.composition}`)},audit:{...base.audit,templateHash:plan.templateHash,projectionHash:plan.projectionHash}};
}
