import type { PoseControlOverrideV1, PoseControlProfile, PoseInteractionInput, PosePersonPlanV2, PosePoint, PoseSafetyResult, PoseScenePlanV2 } from "../pose-v2";

export type LoadSupportPlan={version:'load-support-1';role:'active'|'supported';partnerId:string;phase:string;contactState:'contact'|'approach';loadShare:number;pelvis:PosePoint;torso:PosePoint;footContacts:Array<{joint:number;point:PosePoint}>;source:'story'|'manual';assumptions:string[]};

export type CompositionPolicyV3 = "auto_story" | "preferred" | "locked";
export type VisibilityV3 = "visible" | "occluded" | "out_of_frame" | "unknown";
export type CompositionKindV3 = "head_shoulders" | "chest_action" | "waist_up" | "knee_up" | "full_body" | "environment_full";
export type ActionEvidenceV3 = { id: string; kind: "joint" | "limb" | "relation" | "object" | "support" | "environment"; required: boolean; personIndex?: number; alternatives?: string[]; jointIndices?: number[]; fullPoseJointIndices?: number[]; points?: PosePoint[]; propFootprint?: { propSizeHint?: PoseInteractionInput['propSizeHint']; shape: string; orientation: string; contactSpan: number; hasPoseContact: boolean; regionWidth: number }; relationId?: string; description: string };
export type ProjectionPlanV3 = { id: string; composition: CompositionKindV3; scale: number; translate: PosePoint; viewport: { x: number; y: number; width: number; height: number }; visibility: VisibilityV3[][]; evidenceVisible: Record<string, boolean>; score: number; hardFailures: string[]; source: "auto_story" | "user_preference" | "user_locked" };
export type PoseRelationPlanV3 = PoseInteractionInput & { geometrySource?: 'manual_prop_position'; relationId: string; objectInstanceId: string; actionRelationAudit?: import("./action-relations").ActionRelationAudit; stateBefore: string | null; stateAfter: string | null; occlusionOrder: string[] };
export type PosePersonSemanticV3 = PosePersonPlanV2 & { loadSupport?:LoadSupportPlan;forceSupport?:{version:"force-support-1";axis:PosePoint;lean:PosePoint;footContacts:Array<{joint:number;point:PosePoint}>}; actionGeometryInput?:import("./action-relations").ActionGeometryInput; actionRelationAudit?:import("./action-relations").ActionRelationAudit; pairRole?:"active"|"supported"; actionContacts?:Array<{hand:"left"|"right";target:PosePoint;relationId:string}>; layers?: import("./overlays").PoseLayers; overlayAudit?: import("./overlays").OverlayAudit; basicPoseOverride?: Pick<PoseControlOverrideV1,"bodyView"|"kneeSpacing"|"templateId">; basicGeometry?: import("./basic-geometry").BasicGeometryAudit; secondaryActions: PosePersonPlanV2["actions"]; supportHand: "left" | "right" | null; supportLeg: "left" | "right" | null; targetId: string | null; emotionIntent: string; actionEvidence: ActionEvidenceV3[]; source: { kind: "manual" | "confirmed_visual_spec" | "story_analysis" | "legacy_text"; detail: string }; confidenceScore: number };
export type PoseScenePlanV3 = Omit<PoseScenePlanV2, "schemaVersion" | "people"> & { schemaVersion: "3.0"; plannerVersion: "pose-v3.0.0" | "pose-v3.1.0" | "pose-v3.2.0" | "pose-v3.3.0"; compositionPolicy: CompositionPolicyV3; preferredComposition?: CompositionKindV3; people: PosePersonSemanticV3[]; relations: PoseRelationPlanV3[]; evidence: ActionEvidenceV3[]; fullPeople: PosePoint[][]; projection: ProjectionPlanV3 | null; decisionReasons: string[]; status: "planned" | "needs_pose_edit" | "needs_story_clarification"; inputHash: string; templateHash: string; projectionHash: string | null };
export type PoseControlV3 = { kind: string; posePlanVersion: "3.0"; framingMode: "auto_story"; hiddenJointIndices: number[]; source: "automatic_story_plan"; selectorReason: string; actionFamily: string; presetId: string; variantId: number; scenePlan: PoseScenePlanV3; controlProfile: PoseControlProfile; override: (PoseControlOverrideV1 & { coordinateSpace: "projected_canvas" | "full_pose"; projectionIntent: "lock_current" | "recompute" }) | null; safety: PoseSafetyResult; lowerBodyControl: "full" | "projected_out_of_frame"; framingWarnings: string[]; width: number; height: number; people: PosePoint[][]; fullPeople: PosePoint[][]; visibility: VisibilityV3[][]; svg: string; previews: { fullPoseSvg: string; compositionSvg: string }; artifacts: { controlOpenpose: { mimeType: "image/svg+xml"; width: number; height: number; annotated: false }; controlProp: { required: boolean; relationIds: string[] }; controlSupport: { required: boolean; supportSurfaceIds: string[] } }; audit: { inputHash: string; templateHash: string; projectionHash: string | null; deterministic: true } };
