import {overlayGeometryFailures} from "../../scripts/pose-overlay-guard.mjs";
import type { PosePoint } from "../pose-v2";
import { projectionFramingFailuresV3, evaluateJointEvidenceV3, transformPeopleV3 } from "./projection";
import type { PoseScenePlanV3 } from "./schema";
const d=(a:PosePoint,b:PosePoint)=>Math.hypot(a.x-b.x,a.y-b.y);
export function validatePoseSceneV3(plan:PoseScenePlanV3){const errors:string[]=[...(plan.overrideConflicts||[])],warnings:string[]=[];errors.push(...overlayGeometryFailures(plan.fullPeople,plan.people));if(plan.peopleCount>2)errors.push("v3 automatic planner supports at most two principal characters; use pose editing or upload");if(!plan.projection)errors.push("no composition candidate satisfies the scene");if(plan.projection){
 const current=evaluateJointEvidenceV3(transformPeopleV3(plan.fullPeople,plan.projection.scale,plan.projection.translate),plan.evidence,plan.projection);
 plan.evidence.filter(e=>e.required&&!current[e.id]).forEach(e=>errors.push(`required evidence out of frame: ${e.id}`));
 errors.push(...projectionFramingFailuresV3(transformPeopleV3(plan.fullPeople,plan.projection.scale,plan.projection.translate),plan.projection.composition));
 plan.projection.hardFailures.filter(x=>!x.startsWith('required evidence out of frame:')&&!x.startsWith('requested ')).forEach(x=>errors.push(x));
}plan.relationConflicts.forEach(x=>errors.push(`${x.characterId}:${x.hand} is assigned to multiple relations`));plan.relations.forEach(r=>{const c=r.contactAnchors||[];if(r.handMode==="two"){const l=c.find(x=>x.hand==="left"),q=c.find(x=>x.hand==="right");if(!l||!q)errors.push(`${r.relationId}: two-hand relation requires distinct anchors`);else if(d(l,q)<.025)errors.push(`${r.relationId}: two-hand anchors collapse to one point`)}if(!r.required)warnings.push(`${r.relationId}: optional relation is not a hard constraint`)});plan.people.forEach((person,pi)=>{const audit=person.basicGeometry;if(!audit)return;if(!audit.supported)errors.push(`${person.characterId}: unsupported basic posture requires pose editing`);warnings.push(...audit.warnings);const joints=plan.fullPeople[pi];if(!joints)return;for(const contact of audit.contacts){const joint=joints[contact.joint];if(joint&&d(joint,contact.point)>.025)warnings.push(`${person.characterId}: edited support joint ${contact.joint} differs from its planned contact`)}const hips=joints[8]&&joints[11]?{x:(joints[8].x+joints[11].x)/2,y:(joints[8].y+joints[11].y)/2}:null;if(hips&&d(hips,person.supportRelation.pelvisAnchor)>.025)warnings.push(`${person.characterId}: edited pelvis differs from planned support`)});plan.fullPeople.forEach((p,pi)=>{if(p.some(q=>!Number.isFinite(q.x)||!Number.isFinite(q.y)))errors.push(`person ${pi} contains non-finite joints`);if(p.length<18)errors.push(`person ${pi} has fewer than 18 joints`);[[2,3],[3,4],[5,6],[6,7],[8,9],[9,10],[11,12],[12,13]].forEach(([a,b])=>{if(p[a]&&p[b]&&d(p[a],p[b])>.42)errors.push(`person ${pi} limb ${a}-${b} exceeds reachable range`)})});return{valid:errors.length===0,errors,warnings,contactError:null}}
export function assertProjectionConsistencyV3(plan:PoseScenePlanV3,projected:PosePoint[][]){const e:string[]=[];if(!plan.projection)return["missing projection"];if(projected.length!==plan.fullPeople.length)e.push("projection changed character count");projected.forEach((p,i)=>{if(p.length!==plan.fullPeople[i]?.length)e.push(`projection changed topology for person ${i}`)});return e}
